#!/usr/bin/env bash

NOMBRE=""

yey() {
    toilet --gay --font smmono9 "$1"
}

greeting() {
    echo "Hola! Escribe tu nombre"
    read -rp "Nombre: " nombre
    NOMBRE=$nombre

    yey "Mucho gusto $nombre!"
    yey "Yo soy Gadevoir"
    echo
    echo "Elije que mates quieres hacer."
    echo
}

select-operacion() {
    local msg="Escribe <S> para suma, <R> para resta, <M> para multiplicación o <D> para división"
    read -r -p "$msg: " operacion

    case "${operacion}" in
    s | S)
        suma
        ;;
    d | D)
        division
        ;;
    r | R)
        resta
        ;;
    m | M)
        multiplicacion
        ;;
    esac
}

rand() {
    local min=$1
    local max=$2
    echo $((min + RANDOM % $((max - min))))
}

success() {
    echo
    yey "Muy bien echo $NOMBRE !!"
    echo
}

error() {
    echo
    yey "Oh No!"
    echo "El resultado era $1"
    echo
}

suma() {
    a=$(rand 0 1000)
    b=$(rand 0 1000)
    r=$((a + b))
    read -rp "Cuánto es $a + $b = " ans
    [ $r == "$ans" ] && success || error $r
}

resta() {
    a=$(rand 100 1000)
    b=$(rand 0 a)
    r=$((a - b))
    read -rp "Cuánto es $a - $b = " ans
    [ $r == "$ans" ] && success || error $r
}

multiplicacion() {
    a=$(rand 0 11)
    b=$(rand 0 11)
    r=$((a * b))
    read -rp "Cuánto es $a x $b = " ans
    [ $r == "$ans" ] && success || error $r
}

division() {
    a=$(rand 10 1000)
    b=$(rand 1 10)
    r=$((a / b))
    s=$((a % b))
    read -rp "Cuánto es $a / $b = " ans1
    read -rp "Y el resto? " ans2
    [ $r == "$ans1" ] && [ $s == "$ans2" ] && success || error "$r (con resto $s)"
}

gadevoir() {
    clear
    greeting
    

    while :; do
        select-operacion
        echo
        read -rp "Presiona la tecla <enter> para continuar o <Q> para salir: " r
        [[ "$r" == "q" ]] && break
        clear
    done
}

gadevoir
